on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: 'npm install, build, and test'
      run: |
        echo 'PUBLISH_PROFILE=${{ secrets.azureWebAppPublishProfile}}' >> $GITHUB_ENV 
        npm prune --production
        npm install
        npm run build --if-present
      # npm run test --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@testing
      with:
        app-name: testfebtimeout
        publish-profile: ${{ env.PUBLISH_PROFILE }}
